### ISSUE TITLE
setting fees

### ISSUE THREAD

**Issue by ameba23** [blockades/mmt-metadata#16]
currently the fee is estimated based on ec.getFeeRate and the size of an example transaction.  This could be improved (estimate the transaction size more accurately) - but do we not need to consider setting the fee closer to the time of broadcasting?  as in can we modify it before the last co-signer signs?  i dont see why not...

**Comment by nikolai-b** [comment]
We cannot alter the fee, it is the difference between the value of inputs and outputs so altering it would require everyone to a new transaction.
