### ISSUE TITLE
Connect `signMmtPaymentTest`

### ISSUE THREAD

**Issue by nikolai-b** [blockades/mmt-metadata#9]
Display `initiateMmtPaymentTest` messages, pull the pay to address and the amount from the transaction and have a button to sign the transaction.  
@ameba23 would this then:
1. pass in the transaction to electrum
1. get meta data:
i. pay to address (maybe some into about that address) 
ii. amount
ii current state of that transaction (i.e. has it already been submitted to the block chain)
1. get electrum to sign the transaction
1. grab the newly signed transaction
1. emmit a `signMmtPaymentTest` message with the signed transaction.

**Comment by ameba23** [comment]
exactly. 

the thing thats stopping this being possible right now is im not sure how to get the transaction id from the transaction data we get back from electrum when we initiate a payment.  Its possible to see it in the electrum gui and im pretty sure its just the hash of the transaction data minus the signature, because both signed and partially signed transaction have the same transaction id.

**Comment by ameba23** [comment]
In case its interesting, here is the deserialised transaction data from a testnet payment i just initiated with our app.  The most interesting bit being the signatures - its an array with nice 'null' placeholders for the missing ones.

```
{
    "result": {
        "version": 1,
        "inputs": [
            {
                "prevout_hash": "ec66749cd19a65017aa20cfed0ec23deb303871c438b32e8ce1c57de138892d0",
                "prevout_n": 0,
                "sequence": 4294967293,
                "x_pubkeys": [
                    "ff025754830103137db08000000108b09ad98221472c595df149344faa44de3368a6262563feec407f261eb0ed370314f5676cd3b80381348b056198ddbad64c872d4b88d68543b9f3917138607dec00000000",
                    "ff0257548301159633f880000001acc03c2fdf4864c7c0e6ca8440c1147f3770b3687afcc4b2dbccd32e21c56d540323de4428ad49a0d8187e1f8c67cb044aafdd9e5622aac1bfd57ced20b804792500000000",
                    "ff0257548301d35ef2c7800000014ddcba5db74b19416a8907c5fe8d0f0762411d006caeaaa544e3f28915d5db85029918860498d808533baaa77e0fee7f356ea7aa12ac3f9facd41dc0437323633600000000"
                ],
                "pubkeys": [
                    "022c75aabf3105326e2fdc7d21c97476a11fcfa78c8c5e90937d6f47e03b2060f4",
                    "02abe84ef239aff80757b540709973b0eb7c2e98fa4fbbcf677d34c9cdcaf7c8fb",
                    "02d8d3205a114d80c3f5cd1435f47647ca206953c7777c0f01fe2a3bf11690b406"
                ],
                "signatures": [
                    null,
                    "3045022100d29a79ea9967f7aed1cbef6e30fde03c3ab61bbb5ce1659c52d20ba2e74b974802207f325738e472dcc11671e8df9a4984761e47270e7e2d9638d3cd2133fd3b547101",
                    null
                ],
                "address": "tb1qpyswsc0sg3jdd8jycc46vh86k6qs0h76vlm9jrj88uxe54vvgr7snpd9ez",
                "num_sig": 2,
                "type": "p2wsh",
                "scriptSig": "",
                "value": 405174,
                "witness": "050001ff483045022100d29a79ea9967f7aed1cbef6e30fde03c3ab61bbb5ce1659c52d20ba2e74b974802207f325738e472dcc11671e8df9a4984761e47270e7e2d9638d3cd2133fd3b54710101fffd0201524c53ff025754830103137db08000000108b09ad98221472c595df149344faa44de3368a6262563feec407f261eb0ed370314f5676cd3b80381348b056198ddbad64c872d4b88d68543b9f3917138607dec000000004c53ff0257548301159633f880000001acc03c2fdf4864c7c0e6ca8440c1147f3770b3687afcc4b2dbccd32e21c56d540323de4428ad49a0d8187e1f8c67cb044aafdd9e5622aac1bfd57ced20b8047925000000004c53ff0257548301d35ef2c7800000014ddcba5db74b19416a8907c5fe8d0f0762411d006caeaaa544e3f28915d5db85029918860498d808533baaa77e0fee7f356ea7aa12ac3f9facd41dc043732363360000000053ae",
                "witnessScript": "5221022c75aabf3105326e2fdc7d21c97476a11fcfa78c8c5e90937d6f47e03b2060f42102abe84ef239aff80757b540709973b0eb7c2e98fa4fbbcf677d34c9cdcaf7c8fb2102d8d3205a114d80c3f5cd1435f47647ca206953c7777c0f01fe2a3bf11690b40653ae"
            }
        ],
        "outputs": [
            {
                "value": 59999,
                "type": 0,
                "address": "tb1qj0n763cnjl6pkrx5wl7pzpjyexvt9pn58775zjwtwg68c2fuknyqzv6h28",
                "scriptPubKey": "002093e7ed471397f41b0cd477fc110644c998b286743fbd4149cb72347c293cb4c8",
                "prevout_n": 0
            },
            {
                "value": 344974,
                "type": 0,
                "address": "tb1qykhzdq6yezs2cup574et2t02r8xuyx8v9vdmxz8uga6706u2paaq7p8ash",
                "scriptPubKey": "002025ae268344c8a0ac7034f572b52dea19cdc218ec2b1bb308fc4775e7eb8a0f7a",
                "prevout_n": 1
            }
        ],
        "lockTime": 1316368
    },
    "id": "curltext",
    "error": null
}
```

**Comment by nikolai-b** [comment]
Nice.  Looks like the electrum code is https://github.com/spesmilo/electrum/blob/master/lib/transaction.py#L446 

Is the transaction ID buried in the `witness` ?

**Comment by nikolai-b** [comment]
Is https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-utxo-get-address what we need but it looks deprecated / removed :confused:

**Comment by ameba23** [comment]
https://bitcoin.stackexchange.com/questions/32765/how-do-i-calculate-the-txid-of-this-raw-transaction

**Comment by ameba23** [comment]
https://github.com/spesmilo/electrum/blob/7218bf1d14f963c7f35cb6649677ef4eee4cfa20/lib/transaction.py#L953   ?

**Comment by ameba23** [comment]
i think the [::-1] in python means reverse the order of list items (!?).  do we have to read the raw transaction backwards before taking the hash!??

**Comment by ameba23** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/762

**Comment by ameba23** [comment]
https://gist.github.com/assafshomer/bda3076d48cf66a588f6#file-txid-js-L36

**Comment by ameba23** [comment]
adding these links for future reference:
[nikolais question on bitcointalk.org](https://bitcointalk.org/index.php?topic=4368689.new#new)
https://bitcoin.stackexchange.com/questions/62044/how-to-compute-segwit-txid

**Comment by ameba23** [comment]
i had forgotten about this:

https://viewer.scuttlebot.io/%25EzwYMOeQ9RkKRpylOk45Bc%2FI1HIVdrGXXEON%2BGvdtnw%3D.sha256
